/* Project Euler: Problem 2
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

var limit = 4000000;
var a = 1;
var b = 1;
var c = 0;
var sumEven = 0;


while (a <= limit) {
  if (a % 2 === 0) {
    sumEven+= a;
  }
  c = a + b;
  a = b;
  b = c;
}

console.log(sumEven);